from sqlalchemy.orm import Session
from app.db.models import FoodCommodity, PackagingMaterial, User
from app.core.security import get_password_hash

FOOD_COMMODITIES_DATA = [
    # =========================================================================
    # 1. FRESH PRODUCE (FRUITS & VEGETABLES)
    # =========================================================================
    {
        "name": "Alphonso Mango",
        "category": "Fresh Produce",
        "subcategory": "Tropical Fruits",
        "moisture_content": 83.0,
        "fat_content": 0.4,
        "ph": 4.5,
        "water_activity": 0.98,
        "is_respiring": True,
        "respiration_rate_o2": 45.0,
        "respiration_rate_co2": 52.0,
        "respiration_quotient": 1.15,
        "respiration_class": "HIGH",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "HIGH",
        "optimal_temp_min": 12.0,
        "optimal_temp_max": 14.0,
        "optimal_rh_min": 85.0,
        "optimal_rh_max": 90.0,
        "baseline_shelf_life_ambient_days": 5.0,
        "baseline_shelf_life_refrigerated_days": 21.0,
        "optimal_map_o2_pct": 4.0,
        "optimal_map_co2_pct": 5.0,
        "optimal_map_n2_pct": 91.0,
        "description": "High-value GI-tagged tropical fruit. Highly susceptible to chilling injury below 10°C, rapid ripening via ethylene, and anthracnose rot.",
        "degradation_mechanisms": ["Ethylene Ripening", "Anthracnose Rot", "Chilling Injury", "Weight Loss"]
    },
    {
        "name": "Fresh Strawberries",
        "category": "Fresh Produce",
        "subcategory": "Berries",
        "moisture_content": 91.0,
        "fat_content": 0.3,
        "ph": 3.6,
        "water_activity": 0.99,
        "is_respiring": True,
        "respiration_rate_o2": 65.0,
        "respiration_rate_co2": 78.0,
        "respiration_quotient": 1.2,
        "respiration_class": "VERY_HIGH",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "LOW",
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "optimal_rh_min": 90.0,
        "optimal_rh_max": 95.0,
        "baseline_shelf_life_ambient_days": 1.5,
        "baseline_shelf_life_refrigerated_days": 8.0,
        "optimal_map_o2_pct": 5.0,
        "optimal_map_co2_pct": 12.0,
        "optimal_map_n2_pct": 83.0,
        "description": "Extremely perishable non-climacteric soft fruit. High susceptibility to Botrytis cinerea (gray mold) and moisture desiccation.",
        "degradation_mechanisms": ["Botrytis Gray Mold", "Tissue Softening", "Moisture Transpiration"]
    },
    {
        "name": "Button Mushrooms",
        "category": "Fresh Produce",
        "subcategory": "Fungi",
        "moisture_content": 92.5,
        "fat_content": 0.3,
        "ph": 6.7,
        "water_activity": 0.99,
        "is_respiring": True,
        "respiration_rate_o2": 120.0,
        "respiration_rate_co2": 135.0,
        "respiration_quotient": 1.12,
        "respiration_class": "EXTREMELY_HIGH",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "LOW",
        "optimal_temp_min": 1.0,
        "optimal_temp_max": 4.0,
        "optimal_rh_min": 92.0,
        "optimal_rh_max": 96.0,
        "baseline_shelf_life_ambient_days": 1.0,
        "baseline_shelf_life_refrigerated_days": 6.0,
        "optimal_map_o2_pct": 3.0,
        "optimal_map_co2_pct": 8.0,
        "optimal_map_n2_pct": 89.0,
        "description": "Extremely high respiration rate and polyphenol oxidase (PPO) enzyme activity causing rapid cap browning and veil opening.",
        "degradation_mechanisms": ["Enzymatic Browning (PPO)", "Veil Opening", "Bacterial Blotching"]
    },
    {
        "name": "Fresh Spinach (Baby Leaves)",
        "category": "Fresh Produce",
        "subcategory": "Leafy Greens",
        "moisture_content": 91.5,
        "fat_content": 0.4,
        "ph": 6.5,
        "water_activity": 0.99,
        "is_respiring": True,
        "respiration_rate_o2": 95.0,
        "respiration_rate_co2": 105.0,
        "respiration_quotient": 1.1,
        "respiration_class": "VERY_HIGH",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "HIGH",
        "optimal_temp_min": 0.5,
        "optimal_temp_max": 3.0,
        "optimal_rh_min": 95.0,
        "optimal_rh_max": 98.0,
        "baseline_shelf_life_ambient_days": 1.5,
        "baseline_shelf_life_refrigerated_days": 10.0,
        "optimal_map_o2_pct": 2.5,
        "optimal_map_co2_pct": 7.0,
        "optimal_map_n2_pct": 90.5,
        "description": "High surface-to-volume ratio causes rapid wilting, chlorophyll degradation, and microbial slime formation under high humidity.",
        "degradation_mechanisms": ["Wilting / Moisture Loss", "Chlorophyll Yellowing", "Pseudomonas Rot"]
    },
    {
        "name": "Fresh Tomato (Cluster / Vine)",
        "category": "Fresh Produce",
        "subcategory": "Solanaceous",
        "moisture_content": 94.0,
        "fat_content": 0.2,
        "ph": 4.4,
        "water_activity": 0.99,
        "is_respiring": True,
        "respiration_rate_o2": 28.0,
        "respiration_rate_co2": 32.0,
        "respiration_quotient": 1.14,
        "respiration_class": "MODERATE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "HIGH",
        "optimal_temp_min": 10.0,
        "optimal_temp_max": 13.0,
        "optimal_rh_min": 85.0,
        "optimal_rh_max": 90.0,
        "baseline_shelf_life_ambient_days": 7.0,
        "baseline_shelf_life_refrigerated_days": 20.0,
        "optimal_map_o2_pct": 4.0,
        "optimal_map_co2_pct": 4.0,
        "optimal_map_n2_pct": 92.0,
        "description": "Climacteric fruit. Sensitive to chilling injury below 8°C (causes flavor loss and water-soaked lesions).",
        "degradation_mechanisms": ["Softening", "Skin Cracking", "Alternaria Rot"]
    },
    {
        "name": "Kashmir Apple (Red Delicious)",
        "category": "Fresh Produce",
        "subcategory": "Pome Fruits",
        "moisture_content": 85.0,
        "fat_content": 0.2,
        "ph": 3.8,
        "water_activity": 0.98,
        "is_respiring": True,
        "respiration_rate_o2": 15.0,
        "respiration_rate_co2": 18.0,
        "respiration_quotient": 1.2,
        "respiration_class": "LOW",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "HIGH",
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "optimal_rh_min": 90.0,
        "optimal_rh_max": 95.0,
        "baseline_shelf_life_ambient_days": 14.0,
        "baseline_shelf_life_refrigerated_days": 90.0,
        "optimal_map_o2_pct": 2.0,
        "optimal_map_co2_pct": 2.0,
        "optimal_map_n2_pct": 96.0,
        "description": "High storage stability. Responds well to controlled/modified atmospheres to delay starch-to-sugar conversion and internal breakdown.",
        "degradation_mechanisms": ["Moisture Loss / Shrivelling", "Flesh Mealiness", "Superficial Scald"]
    },
    {
        "name": "Nagpur Mandarin / Orange",
        "category": "Fresh Produce",
        "subcategory": "Citrus",
        "moisture_content": 87.0,
        "fat_content": 0.2,
        "ph": 3.4,
        "water_activity": 0.98,
        "is_respiring": True,
        "respiration_rate_o2": 20.0,
        "respiration_rate_co2": 22.0,
        "respiration_quotient": 1.1,
        "respiration_class": "LOW",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "LOW",
        "optimal_temp_min": 5.0,
        "optimal_temp_max": 8.0,
        "optimal_rh_min": 85.0,
        "optimal_rh_max": 90.0,
        "baseline_shelf_life_ambient_days": 8.0,
        "baseline_shelf_life_refrigerated_days": 30.0,
        "optimal_map_o2_pct": 5.0,
        "optimal_map_co2_pct": 3.0,
        "optimal_map_n2_pct": 92.0,
        "description": "Non-climacteric fruit. Penicillium digitatum (green mold) and water loss from rind flavedo are primary failure modes.",
        "degradation_mechanisms": ["Green Mold (Penicillium)", "Rind Desiccation", "Stem-End Rot"]
    },
    {
        "name": "Cavendish Banana (Yellow / Ripe)",
        "category": "Fresh Produce",
        "subcategory": "Tropical Fruits",
        "moisture_content": 75.0,
        "fat_content": 0.3,
        "ph": 4.8,
        "water_activity": 0.97,
        "is_respiring": True,
        "respiration_rate_o2": 60.0,
        "respiration_rate_co2": 72.0,
        "respiration_quotient": 1.2,
        "respiration_class": "HIGH",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "CRITICAL",
        "optimal_temp_min": 13.0,
        "optimal_temp_max": 15.0,
        "optimal_rh_min": 85.0,
        "optimal_rh_max": 90.0,
        "baseline_shelf_life_ambient_days": 4.0,
        "baseline_shelf_life_refrigerated_days": 12.0,
        "optimal_map_o2_pct": 3.0,
        "optimal_map_co2_pct": 5.0,
        "optimal_map_n2_pct": 92.0,
        "description": "Extremely climacteric. Severe chilling injury below 12°C causing peel browning. Requires high-barrier ethylene scavenging film.",
        "degradation_mechanisms": ["Peel Senescence Browning", "Crown Rot", "Pectin Breakdown", "Chilling Injury"]
    },
    {
        "name": "Thompson Seedless Grapes",
        "category": "Fresh Produce",
        "subcategory": "Berries",
        "moisture_content": 81.0,
        "fat_content": 0.2,
        "ph": 3.8,
        "water_activity": 0.98,
        "is_respiring": True,
        "respiration_rate_o2": 18.0,
        "respiration_rate_co2": 21.0,
        "respiration_quotient": 1.16,
        "respiration_class": "LOW",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "LOW",
        "optimal_temp_min": -0.5,
        "optimal_temp_max": 1.0,
        "optimal_rh_min": 90.0,
        "optimal_rh_max": 95.0,
        "baseline_shelf_life_ambient_days": 3.0,
        "baseline_shelf_life_refrigerated_days": 45.0,
        "optimal_map_o2_pct": 5.0,
        "optimal_map_co2_pct": 10.0,
        "optimal_map_n2_pct": 85.0,
        "description": "Highly vulnerable to Gray Mold (Botrytis cinerea) and rachis stem browning. Requires SO2 generator pad and anti-fog micro-perforated liner.",
        "degradation_mechanisms": ["Gray Mold", "Rachis Browning", "Berry Shatter"]
    },
    {
        "name": "Fresh Green Chillies (G4)",
        "category": "Fresh Produce",
        "subcategory": "Spices & Condiments",
        "moisture_content": 88.0,
        "fat_content": 0.5,
        "ph": 5.2,
        "water_activity": 0.98,
        "is_respiring": True,
        "respiration_rate_o2": 35.0,
        "respiration_rate_co2": 40.0,
        "respiration_quotient": 1.14,
        "respiration_class": "MODERATE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "MEDIUM",
        "optimal_temp_min": 7.0,
        "optimal_temp_max": 10.0,
        "optimal_rh_min": 90.0,
        "optimal_rh_max": 95.0,
        "baseline_shelf_life_ambient_days": 4.0,
        "baseline_shelf_life_refrigerated_days": 18.0,
        "optimal_map_o2_pct": 3.0,
        "optimal_map_co2_pct": 5.0,
        "optimal_map_n2_pct": 92.0,
        "description": "Capsaicin-rich export spice. Calyx rot, chlorophyll loss (turning red), and moisture shrivelling are primary export issues.",
        "degradation_mechanisms": ["Pedicel Calyx Rot", "Color Transition to Red", "Dehydration Wrinkling"]
    },
    {
        "name": "Fresh Pomegranate Arils (Ready-to-Eat)",
        "category": "Fresh Produce",
        "subcategory": "Minimally Processed",
        "moisture_content": 82.0,
        "fat_content": 0.6,
        "ph": 3.2,
        "water_activity": 0.98,
        "is_respiring": True,
        "respiration_rate_o2": 40.0,
        "respiration_rate_co2": 48.0,
        "respiration_quotient": 1.2,
        "respiration_class": "MODERATE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "LOW",
        "optimal_temp_min": 2.0,
        "optimal_temp_max": 4.0,
        "optimal_rh_min": 90.0,
        "optimal_rh_max": 95.0,
        "baseline_shelf_life_ambient_days": 1.0,
        "baseline_shelf_life_refrigerated_days": 14.0,
        "optimal_map_o2_pct": 4.0,
        "optimal_map_co2_pct": 8.0,
        "optimal_map_n2_pct": 88.0,
        "description": "Pre-extracted arils with high anthocyanin pigments. Sensitive to aerobic yeast fermentation and juice leakage.",
        "degradation_mechanisms": ["Anthocyanin Bleaching", "Juice Exudation", "Yeast Fermentation"]
    },
    {
        "name": "Fresh Broccoli Florets",
        "category": "Fresh Produce",
        "subcategory": "Cruciferous",
        "moisture_content": 90.0,
        "fat_content": 0.4,
        "ph": 6.4,
        "water_activity": 0.99,
        "is_respiring": True,
        "respiration_rate_o2": 110.0,
        "respiration_rate_co2": 125.0,
        "respiration_quotient": 1.13,
        "respiration_class": "EXTREMELY_HIGH",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "CRITICAL",
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "optimal_rh_min": 95.0,
        "optimal_rh_max": 98.0,
        "baseline_shelf_life_ambient_days": 1.0,
        "baseline_shelf_life_refrigerated_days": 10.0,
        "optimal_map_o2_pct": 2.0,
        "optimal_map_co2_pct": 8.0,
        "optimal_map_n2_pct": 90.0,
        "description": "Rapid sepals yellowing, off-odor sulfide volatile release if oxygen drops < 1.0%. Requires high gas permeability and anti-fog film.",
        "degradation_mechanisms": ["Sepal Yellowing", "Methanethiol Off-Odor", "Tissue Toughening"]
    },

    # =========================================================================
    # 2. SNACKS, NAMKEEN & READY-TO-EAT (RTE)
    # =========================================================================
    {
        "name": "Potato Crisps / Chips",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Fried Snacks",
        "moisture_content": 2.0,
        "fat_content": 34.0,
        "ph": 6.0,
        "water_activity": 0.18,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "CRITICAL",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 25.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 10.0,
        "baseline_shelf_life_refrigerated_days": 30.0,
        "optimal_map_o2_pct": 0.5,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.5,
        "description": "Extremely hygroscopic and high lipid content. Moisture gain > 3.5% causes sogginess; oxygen exposure causes hexanal rancidity.",
        "degradation_mechanisms": ["Moisture Gain / Loss of Crispness", "Lipid Auto-Oxidation", "Rancidity", "Photo-Oxidation"]
    },
    {
        "name": "Roasted Cashews / Salted Almonds",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Tree Nuts",
        "moisture_content": 3.5,
        "fat_content": 48.0,
        "ph": 6.4,
        "water_activity": 0.28,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "CRITICAL",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 15.0,
        "optimal_temp_max": 22.0,
        "optimal_rh_min": 45.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 20.0,
        "baseline_shelf_life_refrigerated_days": 120.0,
        "optimal_map_o2_pct": 0.5,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.5,
        "description": "High polyunsaturated and monounsaturated fatty acid profile. Very vulnerable to oxidative rancidity and off-flavor development.",
        "degradation_mechanisms": ["Lipid Peroxidation", "Moisture Sorption", "Off-Flavor Development"]
    },
    {
        "name": "Indian Bhujia / Sev Namkeen",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Extruded Fried Snacks",
        "moisture_content": 2.8,
        "fat_content": 38.0,
        "ph": 6.2,
        "water_activity": 0.22,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 28.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 65.0,
        "baseline_shelf_life_ambient_days": 15.0,
        "baseline_shelf_life_refrigerated_days": 45.0,
        "optimal_map_o2_pct": 1.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.0,
        "description": "Chickpea flour-based deep-fried snack seasoned with spices. Needs nitrogen flush and high moisture-oxygen barrier.",
        "degradation_mechanisms": ["Oil Rancidity", "Crunch Loss", "Spice Flavor Fade"]
    },
    {
        "name": "Roasted Makhana (Fox Nuts)",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Healthy Puffed Snacks",
        "moisture_content": 3.0,
        "fat_content": 12.0,
        "ph": 6.6,
        "water_activity": 0.20,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 26.0,
        "optimal_rh_min": 35.0,
        "optimal_rh_max": 55.0,
        "baseline_shelf_life_ambient_days": 15.0,
        "baseline_shelf_life_refrigerated_days": 60.0,
        "optimal_map_o2_pct": 1.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.0,
        "description": "Puffed lotus seed snack. Extremely sponge-like porosity causes rapid moisture pickup and loss of chewiness within hours in humid air.",
        "degradation_mechanisms": ["Rapid Moisture Sorption", "Chewy Texture Collapse", "Seasoning Degradation"]
    },
    {
        "name": "Kerala Banana Chips (Coconut Oil)",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Fried Wafers",
        "moisture_content": 2.5,
        "fat_content": 30.0,
        "ph": 5.8,
        "water_activity": 0.20,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 26.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 20.0,
        "baseline_shelf_life_refrigerated_days": 60.0,
        "optimal_map_o2_pct": 0.5,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.5,
        "description": "Deep fried in pure coconut oil with turmeric. Coconut oil fatty acids undergo hydrolytic and ketonic rancidity under light.",
        "degradation_mechanisms": ["Ketonic Rancidity", "Crunch Depletion", "Turmeric Photo-Fade"]
    },
    {
        "name": "Khakhra (Crispy Gujarati Flatbread)",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Roasted Flatbreads",
        "moisture_content": 4.0,
        "fat_content": 14.0,
        "ph": 6.2,
        "water_activity": 0.30,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 28.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 30.0,
        "baseline_shelf_life_refrigerated_days": 90.0,
        "optimal_map_o2_pct": 1.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.0,
        "description": "Thin roasted wheat crispbread. Requires vacuum packaging or nitrogen flush to prevent breakage and moisture softening.",
        "degradation_mechanisms": ["Sogginess", "Mechanical Fracture / Breakage", "Oil Oxidation"]
    },
    {
        "name": "Ready-to-Eat Dal Makhani (Retort MRE Pouch)",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Retort Meals",
        "moisture_content": 72.0,
        "fat_content": 9.5,
        "ph": 5.8,
        "water_activity": 0.98,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 28.0,
        "optimal_rh_min": 50.0,
        "optimal_rh_max": 75.0,
        "baseline_shelf_life_ambient_days": 180.0,
        "baseline_shelf_life_refrigerated_days": 365.0,
        "optimal_map_o2_pct": 0.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 100.0,
        "description": "Thermally sterilized shelf-stable ready meal. Requires high-barrier retort pouch (121°C sterilization grade, zero gas transmission).",
        "degradation_mechanisms": ["Retort Flavor Scalping", "Lipid Oxidation", "Pouch Delamination"]
    },

    # =========================================================================
    # 3. DAIRY, FATS & TRADITIONAL SWEETS
    # =========================================================================
    {
        "name": "Fresh Paneer (Cottage Cheese)",
        "category": "Dairy",
        "subcategory": "Fresh Soft Cheese",
        "moisture_content": 54.0,
        "fat_content": 24.0,
        "ph": 5.8,
        "water_activity": 0.97,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 2.0,
        "optimal_temp_max": 5.0,
        "optimal_rh_min": 85.0,
        "optimal_rh_max": 90.0,
        "baseline_shelf_life_ambient_days": 1.0,
        "baseline_shelf_life_refrigerated_days": 6.0,
        "optimal_map_o2_pct": 0.2,
        "optimal_map_co2_pct": 30.0,
        "optimal_map_n2_pct": 69.8,
        "description": "Unripened high-moisture acid-coagulated dairy product. Prone to psychrotrophic bacterial spoilage, surface mold, and lipid oxidation.",
        "degradation_mechanisms": ["Psychrotrophic Bacteria", "Surface Yeast & Mold", "Syneresis (Whey Separation)", "Sour Taste"]
    },
    {
        "name": "Desi Ghee (Clarified Butter)",
        "category": "Dairy",
        "subcategory": "Butterfats",
        "moisture_content": 0.3,
        "fat_content": 99.5,
        "ph": 6.8,
        "water_activity": 0.20,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "CRITICAL",
        "moisture_sensitivity": "MEDIUM",
        "light_sensitivity": "CRITICAL",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 25.0,
        "optimal_rh_min": 50.0,
        "optimal_rh_max": 70.0,
        "baseline_shelf_life_ambient_days": 60.0,
        "baseline_shelf_life_refrigerated_days": 270.0,
        "optimal_map_o2_pct": 0.1,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.9,
        "description": "Pure milkfat. Light and oxygen exposure trigger photo-oxidation and free fatty acid generation, ruining granular aroma.",
        "degradation_mechanisms": ["Photo-Oxidation", "Free Fatty Acid Rancidity", "Aroma Depletion"]
    },
    {
        "name": "Cheddar / Mozzarella Cheese",
        "category": "Dairy",
        "subcategory": "Hard & Semi-Hard Cheese",
        "moisture_content": 38.0,
        "fat_content": 32.0,
        "ph": 5.3,
        "water_activity": 0.92,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 2.0,
        "optimal_temp_max": 6.0,
        "optimal_rh_min": 80.0,
        "optimal_rh_max": 85.0,
        "baseline_shelf_life_ambient_days": 3.0,
        "baseline_shelf_life_refrigerated_days": 35.0,
        "optimal_map_o2_pct": 0.2,
        "optimal_map_co2_pct": 30.0,
        "optimal_map_n2_pct": 69.8,
        "description": "Susceptible to anaerobic and aerobic molds (Penicillium). High CO2 headspace inhibits surface fungal colonization.",
        "degradation_mechanisms": ["Mold Colonization", "Lipid Hydrolysis", "Surface Dehydration"]
    },
    {
        "name": "Kaju Katli (Cashew Fudge Sweet)",
        "category": "Dairy",
        "subcategory": "Indian Sweets (Mithai)",
        "moisture_content": 14.0,
        "fat_content": 22.0,
        "ph": 6.5,
        "water_activity": 0.65,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 24.0,
        "optimal_rh_min": 50.0,
        "optimal_rh_max": 65.0,
        "baseline_shelf_life_ambient_days": 10.0,
        "baseline_shelf_life_refrigerated_days": 35.0,
        "optimal_map_o2_pct": 0.2,
        "optimal_map_co2_pct": 20.0,
        "optimal_map_n2_pct": 79.8,
        "description": "Cashew and sugar paste with silver leaf (varak). High intermediate moisture level makes it prone to xerophilic mold growth and rancidity.",
        "degradation_mechanisms": ["Xerophilic Fungal Growth", "Fat Rancidity", "Sugar Recrystallization"]
    },
    {
        "name": "Rasgulla (Cottage Cheese Balls in Syrup)",
        "category": "Dairy",
        "subcategory": "Syrup Sweets",
        "moisture_content": 50.0,
        "fat_content": 5.0,
        "ph": 5.6,
        "water_activity": 0.90,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 25.0,
        "optimal_rh_min": 60.0,
        "optimal_rh_max": 75.0,
        "baseline_shelf_life_ambient_days": 15.0,
        "baseline_shelf_life_refrigerated_days": 90.0,
        "optimal_map_o2_pct": 0.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 100.0,
        "description": "High brix sugar syrup environment. Requires hermetic barrier retort pouch or metal tin to prevent osmotolerant yeast fermentation.",
        "degradation_mechanisms": ["Osmotolerant Yeast Fermentation", "Texture Rubbery", "Syrup Cloudiness"]
    },
    {
        "name": "Milk Powder (Dairy Whitener)",
        "category": "Dairy",
        "subcategory": "Dried Dairy",
        "moisture_content": 3.0,
        "fat_content": 26.0,
        "ph": 6.6,
        "water_activity": 0.20,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "CRITICAL",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 25.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 55.0,
        "baseline_shelf_life_ambient_days": 90.0,
        "baseline_shelf_life_refrigerated_days": 365.0,
        "optimal_map_o2_pct": 0.2,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.8,
        "description": "Spray dried dairy powder. Extremely hygroscopic; caking occurs when aw exceeds 0.35, accompanied by tallowy lipid oxidation.",
        "degradation_mechanisms": ["Lactose Glass Transition / Caking", "Tallowy Oxidation", "Maillard Non-Enzymatic Browning"]
    },

    # =========================================================================
    # 4. MEAT, POULTRY & SEAFOOD
    # =========================================================================
    {
        "name": "Fresh Chicken Breast (Chilled)",
        "category": "Meat & Poultry",
        "subcategory": "Fresh Poultry",
        "moisture_content": 74.0,
        "fat_content": 3.6,
        "ph": 5.9,
        "water_activity": 0.99,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": -1.0,
        "optimal_temp_max": 2.0,
        "optimal_rh_min": 90.0,
        "optimal_rh_max": 95.0,
        "baseline_shelf_life_ambient_days": 0.5,
        "baseline_shelf_life_refrigerated_days": 4.0,
        "optimal_map_o2_pct": 0.0,
        "optimal_map_co2_pct": 30.0,
        "optimal_map_n2_pct": 70.0,
        "description": "High water activity and neutral pH create prime conditions for Pseudomonas and Enterobacteriaceae. Requires high CO2 MAP or vacuum skin pack.",
        "degradation_mechanisms": ["Pseudomonas Putrefaction", "Off-Odor (Sulfides)", "Surface Slime", "Myoglobin Discoloration"]
    },
    {
        "name": "Fresh Raw Prawns / Shrimp",
        "category": "Meat & Poultry",
        "subcategory": "Seafood",
        "moisture_content": 78.0,
        "fat_content": 1.2,
        "ph": 6.8,
        "water_activity": 0.99,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "CRITICAL",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": -1.0,
        "optimal_temp_max": 1.0,
        "optimal_rh_min": 95.0,
        "optimal_rh_max": 98.0,
        "baseline_shelf_life_ambient_days": 0.3,
        "baseline_shelf_life_refrigerated_days": 3.0,
        "optimal_map_o2_pct": 0.0,
        "optimal_map_co2_pct": 40.0,
        "optimal_map_n2_pct": 60.0,
        "description": "Melanosis (black spot) driven by polyphenol oxidase enzymes and rapid trimethylamine (TMA) fishy odor emergence.",
        "degradation_mechanisms": ["Melanosis (Black Spot)", "TMA Spoilage", "Texture Mushiness"]
    },
    {
        "name": "Fresh Rohu Fish Steaks",
        "category": "Meat & Poultry",
        "subcategory": "Freshwater Fish",
        "moisture_content": 77.0,
        "fat_content": 3.0,
        "ph": 6.6,
        "water_activity": 0.99,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": -1.0,
        "optimal_temp_max": 1.0,
        "optimal_rh_min": 95.0,
        "optimal_rh_max": 98.0,
        "baseline_shelf_life_ambient_days": 0.5,
        "baseline_shelf_life_refrigerated_days": 4.0,
        "optimal_map_o2_pct": 0.0,
        "optimal_map_co2_pct": 40.0,
        "optimal_map_n2_pct": 60.0,
        "description": "Major freshwater carp in India. Highly susceptible to autolytic breakdown and Shewanella putrefaciens slime.",
        "degradation_mechanisms": ["Shewanella Bacterial Slime", "Ammonia & TMA Off-Odor", "Gill Discoloration"]
    },
    {
        "name": "Fresh Mutton Cuts (Goat Meat)",
        "category": "Meat & Poultry",
        "subcategory": "Red Meat",
        "moisture_content": 70.0,
        "fat_content": 8.0,
        "ph": 5.8,
        "water_activity": 0.99,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "MEDIUM",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 0.0,
        "optimal_temp_max": 2.0,
        "optimal_rh_min": 85.0,
        "optimal_rh_max": 90.0,
        "baseline_shelf_life_ambient_days": 0.5,
        "baseline_shelf_life_refrigerated_days": 5.0,
        "optimal_map_o2_pct": 70.0,
        "optimal_map_co2_pct": 20.0,
        "optimal_map_n2_pct": 10.0,
        "description": "High-oxygen MAP (70% O2) is used to maintain bright red oxymyoglobin bloom, combined with 20% CO2 for microbial suppression.",
        "degradation_mechanisms": ["Metmyoglobin Met-Browning", "Lipid Oxidation", "Drip Loss"]
    },

    # =========================================================================
    # 5. BAKERY & CONFECTIONERY
    # =========================================================================
    {
        "name": "Sliced White / Wheat Bread",
        "category": "Bakery & Confectionery",
        "subcategory": "Leavened Bread",
        "moisture_content": 36.0,
        "fat_content": 4.0,
        "ph": 5.5,
        "water_activity": 0.95,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 24.0,
        "optimal_rh_min": 60.0,
        "optimal_rh_max": 70.0,
        "baseline_shelf_life_ambient_days": 3.0,
        "baseline_shelf_life_refrigerated_days": 7.0,
        "optimal_map_o2_pct": 0.5,
        "optimal_map_co2_pct": 40.0,
        "optimal_map_n2_pct": 59.5,
        "description": "Starch retrogradation (staling) and mold growth (Rhizopus stolonifer). Refrigeration accelerates staling; MAP with CO2/N2 extends mold-free life.",
        "degradation_mechanisms": ["Rhizopus Mold Spores", "Starch Retrogradation (Staling)", "Moisture Desorption"]
    },
    {
        "name": "Dark Chocolate / Cocoa Bars",
        "category": "Bakery & Confectionery",
        "subcategory": "Confectionery",
        "moisture_content": 1.2,
        "fat_content": 32.0,
        "ph": 5.8,
        "water_activity": 0.35,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 15.0,
        "optimal_temp_max": 18.0,
        "optimal_rh_min": 45.0,
        "optimal_rh_max": 55.0,
        "baseline_shelf_life_ambient_days": 90.0,
        "baseline_shelf_life_refrigerated_days": 365.0,
        "optimal_map_o2_pct": None,
        "optimal_map_co2_pct": None,
        "optimal_map_n2_pct": None,
        "description": "Cocoa butter polymorphism. Moisture condensation causes sugar bloom; temperature fluctuations trigger fat bloom.",
        "degradation_mechanisms": ["Fat Bloom (Polymorphic Transition)", "Sugar Bloom", "Moisture Sorption", "Flavor Absorption"]
    },
    {
        "name": "Butter Cookies / Marie Biscuits",
        "category": "Bakery & Confectionery",
        "subcategory": "Biscuits & Cookies",
        "moisture_content": 2.5,
        "fat_content": 18.0,
        "ph": 6.8,
        "water_activity": 0.22,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 25.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 30.0,
        "baseline_shelf_life_refrigerated_days": 120.0,
        "optimal_map_o2_pct": 1.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.0,
        "description": "High butter/shortening fat content and crisp biscuit matrix. Moisture uptake destroys crunchy snap; light causes oxidative off-taste.",
        "degradation_mechanisms": ["Loss of Snap / Moisture Gain", "Shortening Rancidity", "Mechanical Crumbling"]
    },
    {
        "name": "Whole Wheat Roti / Paratha (Shelf-Stable MAP)",
        "category": "Bakery & Confectionery",
        "subcategory": "Flatbreads",
        "moisture_content": 32.0,
        "fat_content": 6.0,
        "ph": 5.8,
        "water_activity": 0.90,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 24.0,
        "optimal_rh_min": 55.0,
        "optimal_rh_max": 65.0,
        "baseline_shelf_life_ambient_days": 2.0,
        "baseline_shelf_life_refrigerated_days": 30.0,
        "optimal_map_o2_pct": 0.1,
        "optimal_map_co2_pct": 50.0,
        "optimal_map_n2_pct": 49.9,
        "description": "High moisture unleavened flatbread. Ultra-high CO2 (50%) headspace or ethanol vapor emitters prevent mold without refrigeration.",
        "degradation_mechanisms": ["Aspergillus & Penicillium Mold", "Retrogradation Stiffening", "Stickiness"]
    },

    # =========================================================================
    # 6. GRAINS, CEREALS, PULSES & BEVERAGES
    # =========================================================================
    {
        "name": "Basmati Rice (Aged)",
        "category": "Grains & Cereals",
        "subcategory": "Milled Cereals",
        "moisture_content": 12.0,
        "fat_content": 0.8,
        "ph": 6.5,
        "water_activity": 0.58,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 28.0,
        "optimal_rh_min": 50.0,
        "optimal_rh_max": 65.0,
        "baseline_shelf_life_ambient_days": 180.0,
        "baseline_shelf_life_refrigerated_days": 540.0,
        "optimal_map_o2_pct": 0.5,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.5,
        "description": "Moisture absorption > 14% triggers rice weevil (Sitophilus oryzae) egg hatching and mycotoxigenic Aspergillus growth.",
        "degradation_mechanisms": ["Insect Weevil Infestation", "Mold (Aspergillus)", "2-AP Aroma Fade"]
    },
    {
        "name": "Toor Dal (Yellow Split Pigeon Peas)",
        "category": "Grains & Cereals",
        "subcategory": "Pulses & Legumes",
        "moisture_content": 11.0,
        "fat_content": 1.5,
        "ph": 6.6,
        "water_activity": 0.55,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "LOW",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 28.0,
        "optimal_rh_min": 45.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 180.0,
        "baseline_shelf_life_refrigerated_days": 540.0,
        "optimal_map_o2_pct": 0.5,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.5,
        "description": "Split pulse pulse beetle (Callosobruchus chinensis) infestation if exposed to humid air. Hard-to-cook defect if aged > 30°C.",
        "degradation_mechanisms": ["Pulse Beetle Infestation", "Hard-to-Cook Phenomenon", "Color Darkening"]
    },
    {
        "name": "Whole Wheat Chakki Atta",
        "category": "Grains & Cereals",
        "subcategory": "Milled Flours",
        "moisture_content": 11.5,
        "fat_content": 2.2,
        "ph": 6.3,
        "water_activity": 0.58,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "MEDIUM",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "LOW",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 26.0,
        "optimal_rh_min": 45.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 60.0,
        "baseline_shelf_life_refrigerated_days": 180.0,
        "optimal_map_o2_pct": 1.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.0,
        "description": "Contains wheat germ lipases causing enzymatic hydrolysis into free fatty acids. Moisture causes flour clumping and Tribolium beetles.",
        "degradation_mechanisms": ["Lipase Enzymatic Hydrolysis", "Tribolium Castaneum (Red Flour Beetle)", "Clumping"]
    },
    {
        "name": "Roasted & Ground Coffee Beans",
        "category": "Beverages",
        "subcategory": "Roasted Coffee",
        "moisture_content": 2.5,
        "fat_content": 14.0,
        "ph": 5.0,
        "water_activity": 0.25,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "CRITICAL",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 15.0,
        "optimal_temp_max": 22.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 14.0,
        "baseline_shelf_life_refrigerated_days": 90.0,
        "optimal_map_o2_pct": 0.2,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.8,
        "description": "Massive post-roast CO2 degassing and extreme susceptibility to aroma terpene oxidation. Requires one-way degassing valve and triplex foil laminate.",
        "degradation_mechanisms": ["Aroma Volatile Loss", "Lipid Oxidation", "Moisture Pick-up", "Headspace Pressure Build-up"]
    },
    {
        "name": "Darjeeling Orthodox Tea Leaves",
        "category": "Beverages",
        "subcategory": "Specialty Tea",
        "moisture_content": 5.0,
        "fat_content": 0.5,
        "ph": 5.5,
        "water_activity": 0.35,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "CRITICAL",
        "light_sensitivity": "HIGH",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 24.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 55.0,
        "baseline_shelf_life_ambient_days": 120.0,
        "baseline_shelf_life_refrigerated_days": 365.0,
        "optimal_map_o2_pct": 0.5,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.5,
        "description": "Muscatel floral aroma compounds (linalool, geraniol). Moisture sorption > 7% activates polyphenol oxidases, darkening liquor color.",
        "degradation_mechanisms": ["Floral Aroma Depletion", "Theaflavin to Thearubigin Oxidation", "Tallowy Off-Notes"]
    },
    {
        "name": "Turmeric / Red Chilli Powder (Spices)",
        "category": "Snacks & Ready-To-Eat",
        "subcategory": "Ground Spices",
        "moisture_content": 8.0,
        "fat_content": 11.0,
        "ph": 6.0,
        "water_activity": 0.45,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "HIGH",
        "moisture_sensitivity": "HIGH",
        "light_sensitivity": "CRITICAL",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 26.0,
        "optimal_rh_min": 45.0,
        "optimal_rh_max": 60.0,
        "baseline_shelf_life_ambient_days": 90.0,
        "baseline_shelf_life_refrigerated_days": 365.0,
        "optimal_map_o2_pct": 1.0,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.0,
        "description": "Curcumin and capsanthin color pigments degrade rapidly upon exposure to light and oxygen. Moisture causes clumping and caking.",
        "degradation_mechanisms": ["Curcumin Photodegradation", "Volatile Essential Oil Loss", "Caking / Clumping"]
    },
    {
        "name": "Mustard Oil / Cold Pressed Oil (Pouch)",
        "category": "Oils & Fats",
        "subcategory": "Edible Vegetable Oils",
        "moisture_content": 0.1,
        "fat_content": 99.8,
        "ph": 6.5,
        "water_activity": 0.15,
        "is_respiring": False,
        "respiration_rate_o2": 0.0,
        "respiration_rate_co2": 0.0,
        "respiration_quotient": 1.0,
        "respiration_class": "NONE",
        "oxygen_sensitivity": "CRITICAL",
        "moisture_sensitivity": "LOW",
        "light_sensitivity": "CRITICAL",
        "ethylene_sensitivity": "NONE",
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 26.0,
        "optimal_rh_min": 40.0,
        "optimal_rh_max": 70.0,
        "baseline_shelf_life_ambient_days": 180.0,
        "baseline_shelf_life_refrigerated_days": 365.0,
        "optimal_map_o2_pct": 0.1,
        "optimal_map_co2_pct": 0.0,
        "optimal_map_n2_pct": 99.9,
        "description": "Allyl isothiocyanate pungency and polyunsaturated fatty acids. UV light triggers peroxide formation and rancid odor.",
        "degradation_mechanisms": ["Peroxide Auto-Oxidation", "Pungency Volatile Fade", "Polymer Environmental Stress Cracking (ESCR)"]
    }
]

PACKAGING_MATERIALS_DATA = [
    # --- 1. Conventional Flexible Polymers ---
    {
        "name": "Low-Density Polyethylene (LDPE)",
        "code": "LDPE-25",
        "category": "CONVENTIONAL",
        "base_polymer": "LDPE",
        "typical_thickness_um": 25.0,
        "density_g_cm3": 0.92,
        "otr_at_23c": 4500.0, # cc/m²·day·atm
        "wvtr_at_38c": 18.0,  # g/m²·day
        "co2tr_at_23c": 18000.0,
        "tensile_strength_mpa": 25.0,
        "puncture_resistance_n": 12.0,
        "seal_initiation_temp_c": 105.0,
        "transparency_pct": 82.0,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 4,
        "carbon_footprint_kg_co2_per_kg": 2.0,
        "approx_cost_inr_per_kg": 130.0,
        "description": "Workhorse flexible packaging film. Excellent flexibility, low cost, good moisture barrier, high gas permeability.",
        "suitable_applications": ["Bread bags", "Fresh produce bags", "Frozen food inner liners", "Milk pouch sealant"],
        "limitations": ["Poor oxygen barrier", "Low grease resistance"]
    },
    {
        "name": "High-Density Polyethylene (HDPE)",
        "code": "HDPE-30",
        "category": "CONVENTIONAL",
        "base_polymer": "HDPE",
        "typical_thickness_um": 30.0,
        "density_g_cm3": 0.96,
        "otr_at_23c": 1600.0,
        "wvtr_at_38c": 5.5,
        "co2tr_at_23c": 6000.0,
        "tensile_strength_mpa": 42.0,
        "puncture_resistance_n": 18.0,
        "seal_initiation_temp_c": 125.0,
        "transparency_pct": 65.0,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 2,
        "carbon_footprint_kg_co2_per_kg": 1.9,
        "approx_cost_inr_per_kg": 140.0,
        "description": "High tensile strength, stiff translucent film with superior water vapor barrier compared to LDPE.",
        "suitable_applications": ["Cereal box liners", "Bulk grain bags", "Snack pouches", "Bottles"],
        "limitations": ["Lower optical clarity", "Higher seal initiation temperature"]
    },
    {
        "name": "Biaxially Oriented Polypropylene (BOPP)",
        "code": "BOPP-20",
        "category": "CONVENTIONAL",
        "base_polymer": "BOPP",
        "typical_thickness_um": 20.0,
        "density_g_cm3": 0.91,
        "otr_at_23c": 1800.0,
        "wvtr_at_38c": 4.8,
        "co2tr_at_23c": 7500.0,
        "tensile_strength_mpa": 160.0,
        "puncture_resistance_n": 22.0,
        "seal_initiation_temp_c": 130.0,
        "transparency_pct": 92.0,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 5,
        "carbon_footprint_kg_co2_per_kg": 2.2,
        "approx_cost_inr_per_kg": 165.0,
        "description": "Exceptional optical clarity, high tensile stiffness, and excellent moisture barrier. Core outer layer in snack packaging.",
        "suitable_applications": ["Outer print layer for snack laminates", "Confectionery wraps", "Pasta & pulse packaging"],
        "limitations": ["Non-sealable without co-extruded terpolymer layer"]
    },
    {
        "name": "Biaxially Oriented Polyethylene Terephthalate (BOPET)",
        "code": "BOPET-12",
        "category": "CONVENTIONAL",
        "base_polymer": "PET",
        "typical_thickness_um": 12.0,
        "density_g_cm3": 1.40,
        "otr_at_23c": 110.0,
        "wvtr_at_38c": 25.0,
        "co2tr_at_23c": 450.0,
        "tensile_strength_mpa": 220.0,
        "puncture_resistance_n": 28.0,
        "seal_initiation_temp_c": 220.0,
        "transparency_pct": 90.0,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 1,
        "carbon_footprint_kg_co2_per_kg": 2.8,
        "approx_cost_inr_per_kg": 190.0,
        "description": "High thermal stability (up to 200°C), superior dimensional stability, printability, and moderate gas barrier.",
        "suitable_applications": ["Retort pouches", "Stand-up pouches outer layer", "Vacuum skin packaging base"],
        "limitations": ["Requires separate inner sealant layer"]
    },

    # --- 2. High-Barrier & Metallized Films ---
    {
        "name": "Metallized BOPP (Met-BOPP)",
        "code": "MET-BOPP-15",
        "category": "HIGH_BARRIER",
        "base_polymer": "Met-BOPP",
        "typical_thickness_um": 15.0,
        "density_g_cm3": 0.91,
        "otr_at_23c": 18.0,
        "wvtr_at_38c": 0.65,
        "co2tr_at_23c": 80.0,
        "tensile_strength_mpa": 170.0,
        "puncture_resistance_n": 24.0,
        "seal_initiation_temp_c": 120.0,
        "transparency_pct": 0.5,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 5,
        "carbon_footprint_kg_co2_per_kg": 2.4,
        "approx_cost_inr_per_kg": 210.0,
        "description": "Vacuum aluminum metallized film providing high moisture and oxygen barrier + optical opacity for light-sensitive goods.",
        "suitable_applications": ["Potato wafer laminates", "Biscuits", "Namkeen", "Instant noodles"],
        "limitations": ["Opaque, cannot inspect food visually"]
    },
    {
        "name": "Metallized PET (Met-PET)",
        "code": "MET-PET-12",
        "category": "HIGH_BARRIER",
        "base_polymer": "Met-PET",
        "typical_thickness_um": 12.0,
        "density_g_cm3": 1.40,
        "otr_at_23c": 1.2,
        "wvtr_at_38c": 0.85,
        "co2tr_at_23c": 6.0,
        "tensile_strength_mpa": 230.0,
        "puncture_resistance_n": 30.0,
        "seal_initiation_temp_c": 210.0,
        "transparency_pct": 0.2,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 1,
        "carbon_footprint_kg_co2_per_kg": 3.0,
        "approx_cost_inr_per_kg": 230.0,
        "description": "High gas barrier barrier film. Commonly substituted for aluminum foil in lightweight barrier laminates.",
        "suitable_applications": ["Coffee pouches", "Spices", "Milk powder sachets", "High-fat nuts"],
        "limitations": ["Not microwaveable"]
    },
    {
        "name": "Ethylene Vinyl Alcohol (EVOH 32 mol%)",
        "code": "EVOH-15",
        "category": "HIGH_BARRIER",
        "base_polymer": "EVOH",
        "typical_thickness_um": 15.0,
        "density_g_cm3": 1.19,
        "otr_at_23c": 0.3,
        "wvtr_at_38c": 35.0,
        "co2tr_at_23c": 1.5,
        "tensile_strength_mpa": 110.0,
        "puncture_resistance_n": 26.0,
        "seal_initiation_temp_c": 170.0,
        "transparency_pct": 94.0,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 7,
        "carbon_footprint_kg_co2_per_kg": 3.5,
        "approx_cost_inr_per_kg": 420.0,
        "description": "World-class transparent oxygen barrier. Must be sandwiched between polyolefins (PE/PP) to protect against moisture plasticization.",
        "suitable_applications": ["MAP trays for fresh meat", "Cheese packaging", "Sauce barrier bottles", "Retort pouches"],
        "limitations": ["High sensitivity to moisture (>75% RH reduces gas barrier)"]
    },
    {
        "name": "Aluminum Foil (Pure 9µm)",
        "code": "ALU-FOIL-09",
        "category": "HIGH_BARRIER",
        "base_polymer": "Aluminum",
        "typical_thickness_um": 9.0,
        "density_g_cm3": 2.70,
        "otr_at_23c": 0.01,
        "wvtr_at_38c": 0.01,
        "co2tr_at_23c": 0.01,
        "tensile_strength_mpa": 85.0,
        "puncture_resistance_n": 15.0,
        "seal_initiation_temp_c": 660.0,
        "transparency_pct": 0.0,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 7,
        "carbon_footprint_kg_co2_per_kg": 8.5,
        "approx_cost_inr_per_kg": 350.0,
        "description": "Absolute barrier against gases, moisture, light, and aromas. Zero permeation when pinhole-free.",
        "suitable_applications": ["Military MREs", "Aseptic juice cartons (Tetra Pak)", "Pharmaceutical blister packs", "Long-life coffee pouches"],
        "limitations": ["Susceptible to flex-cracking pinholes if bent repeatedly"]
    },

    # --- 3. Biodegradable, Bio-based & Compostable Polymers ---
    {
        "name": "Polylactic Acid Film (PLA)",
        "code": "PLA-BIO-01",
        "category": "BIODEGRADABLE_COMPOSTABLE",
        "base_polymer": "PLA",
        "typical_thickness_um": 25.0,
        "density_g_cm3": 1.25,
        "otr_at_23c": 550.0,
        "wvtr_at_38c": 175.0,
        "co2tr_at_23c": 2200.0,
        "tensile_strength_mpa": 60.0,
        "puncture_resistance_n": 14.0,
        "seal_initiation_temp_c": 85.0,
        "transparency_pct": 95.0,
        "is_biodegradable": True,
        "is_home_compostable": False,
        "is_industrial_compostable": True,
        "recycling_code": 7,
        "carbon_footprint_kg_co2_per_kg": 1.3,
        "compost_timeline_days": 90,
        "approx_cost_inr_per_kg": 240.0,
        "description": "100% bio-based corn-starch derived biopolymer with high clarity, excellent aroma barrier, and industrial compostability (EN 13432).",
        "suitable_applications": ["Fresh produce clamshells", "Dry bakery windows", "Organic tea pouches", "Salad containers"],
        "limitations": ["Brittle without plasticizers", "High moisture transmission rate"]
    },
    {
        "name": "Polybutylene Adipate Terephthalate (PBAT)",
        "code": "PBAT-TPS-01",
        "category": "BIODEGRADABLE_COMPOSTABLE",
        "base_polymer": "PBAT",
        "typical_thickness_um": 35.0,
        "density_g_cm3": 1.22,
        "otr_at_23c": 1200.0,
        "wvtr_at_38c": 120.0,
        "co2tr_at_23c": 5200.0,
        "tensile_strength_mpa": 32.0,
        "puncture_resistance_n": 28.0,
        "seal_initiation_temp_c": 95.0,
        "transparency_pct": 72.0,
        "is_biodegradable": True,
        "is_home_compostable": True,
        "is_industrial_compostable": True,
        "recycling_code": 7,
        "carbon_footprint_kg_co2_per_kg": 1.6,
        "compost_timeline_days": 60,
        "approx_cost_inr_per_kg": 260.0,
        "description": "High elongation, flexible bio-aliphatic polyester. Blended with starch/PLA for home-compostable food carrier bags.",
        "suitable_applications": ["Fresh vegetable and fruit bags", "Agricultural mulch film", "Compostable mailers"],
        "limitations": ["Lower tensile modulus, translucent"]
    },
    {
        "name": "Polyhydroxyalkanoate (PHA)",
        "code": "PHA-BIO-01",
        "category": "BIODEGRADABLE_COMPOSTABLE",
        "base_polymer": "PHA",
        "typical_thickness_um": 25.0,
        "density_g_cm3": 1.20,
        "otr_at_23c": 85.0,
        "wvtr_at_38c": 45.0,
        "co2tr_at_23c": 410.0,
        "tensile_strength_mpa": 38.0,
        "puncture_resistance_n": 20.0,
        "seal_initiation_temp_c": 115.0,
        "transparency_pct": 78.0,
        "is_biodegradable": True,
        "is_home_compostable": True,
        "is_industrial_compostable": True,
        "recycling_code": 7,
        "carbon_footprint_kg_co2_per_kg": 1.1,
        "compost_timeline_days": 45,
        "approx_cost_inr_per_kg": 340.0,
        "description": "Bacterial fermentation-derived biopolymer. Marine-biodegradable and home-compostable with decent moisture & oxygen barrier.",
        "suitable_applications": ["Single-use food wraps", "Cutlery", "Coffee capsule bodies", "Bio-barrier coatings"],
        "limitations": ["Emerging commercial production scale"]
    },

    # --- 4. Breathable & Anti-Fog Films ---
    {
        "name": "Anti-Fog Micro-Perforated BOPP",
        "code": "BOPP-AF-30",
        "category": "BREATHABLE",
        "base_polymer": "BOPP",
        "typical_thickness_um": 30.0,
        "density_g_cm3": 0.91,
        "otr_at_23c": 6500.0, # Tailored with micro-perforations
        "wvtr_at_38c": 12.0,
        "co2tr_at_23c": 24000.0,
        "tensile_strength_mpa": 140.0,
        "puncture_resistance_n": 20.0,
        "seal_initiation_temp_c": 110.0,
        "transparency_pct": 93.0,
        "is_biodegradable": False,
        "is_home_compostable": False,
        "is_industrial_compostable": False,
        "is_recyclable": True,
        "recycling_code": 5,
        "carbon_footprint_kg_co2_per_kg": 2.2,
        "approx_cost_inr_per_kg": 190.0,
        "description": "Engineered anti-fog surfactant coating prevents droplet condensation in refrigerated display while laser micro-perforations maintain O2/CO2 equilibrium.",
        "suitable_applications": ["Fresh cut salads", "Mushrooms", "Berries", "Herbs and cut vegetables"],
        "limitations": ["Not suitable for dry foods or nitrogen flush"]
    }
]

def seed_database(db: Session):
    """Populates database with default commodities, packaging materials, and admin user."""
    
    # 1. Admin User
    existing_user = db.query(User).filter(User.email == "admin@packd.ai").first()
    if not existing_user:
        admin_user = User(
            email="admin@packd.ai",
            password_hash=get_password_hash("Packd2026!"),
            full_name="Dr. Anand Varma",
            organization_name="National Food Packaging Institute (SIH)",
            role="SUPER_ADMIN",
            is_active=True
        )
        db.add(admin_user)
        
    # 2. Food Commodities (Add or update all items)
    for item in FOOD_COMMODITIES_DATA:
        existing = db.query(FoodCommodity).filter(FoodCommodity.name == item["name"]).first()
        if not existing:
            commodity = FoodCommodity(**item)
            db.add(commodity)
        else:
            for k, v in item.items():
                setattr(existing, k, v)
            
    # 3. Packaging Materials
    for item in PACKAGING_MATERIALS_DATA:
        existing = db.query(PackagingMaterial).filter(PackagingMaterial.code == item["code"]).first()
        if not existing:
            mat = PackagingMaterial(**item)
            db.add(mat)
            
    db.commit()
